#ifndef UI_STRINGS_H
#define UI_STRINGS_H

/* English-only UI strings. Chinese/Pinyin language support was removed. */
#define STR_STEP "Step"
#define STR_RXDCS "RxDCS"
#define STR_RXCTCS "RxCTCS"
#define STR_TXDCS "TxDCS"
#define STR_TXCTCS "TxCTCS"
#define STR_TXODIR "TxODir"
#define STR_TXOFFS "TxOffs"
#define STR_SCRAMB "Scramb"
#define STR_BUSYCL "BusyCL"
#define STR_COMPND "Compnd"
#define STR_CHSAVE "ChSave"
#define STR_CHDELE "ChDele"
#define STR_CHNAME "ChName"
#define STR_SLIST "SList"
#define STR_SLIST1 "SList1"
#define STR_SLIST2 "SList2"
#define STR_SCNREV "ScnRev"
#define STR_TXTOUT "TxTOut"
#define STR_BATSAV "BatSav"
#define STR_MIC "Mic"
#define STR_CHDISP "ChDisp"
#define STR_BACKLT "BackLt"
#define STR_LIGHT "Light"
#define STR_ROGER "Roger"
#define STR_STE "STE"
#define STR_RP_STE "RP STE"
#define STR_V_1_CALL "1 Call"
#define STR_UPCODE "UPCode"
#define STR_DWCODE "DWCode"
#define STR_PTT_ID "PTT ID"
#define STR_D_ST "D ST"
#define STR_D_RESP "D Resp"
#define STR_D_HOLD "D Hold"
#define STR_D_PREL "D Prel"
#define STR_D_LIST "D List"
#define STR_D_LIVE "D Live"
#define STR_AM_FIX "AM Fix"
#define STR_RXMODE "RxMode"
#define STR_SQL "Sql"
#define STR_F_LOCK "F Lock"
#define STR_TX_200 "Tx 200"
#define STR_TX_350 "Tx 350"
#define STR_TX_500 "Tx 500"
#define STR_V_350_EN "350 En"
#define STR_BATCAL "BatCal"
#define STR_BATVOL "BatVol"
#define STR_RESET "Reset"
#define STR_OFF "OFF"
#define STR_TX_EQUALS_RX_PLUS "+"
#define STR_TX_EQUALS_RX_MINUS "-"
#define STR_ON "ON"
#define STR_V_1_1 "1:1"
#define STR_V_1_2 "1:2"
#define STR_V_1_3 "1:3"
#define STR_V_1_4 "1:4"
#define STR_V_1_5 "1:5"
#define STR_V_1_6 "1:6"
#define STR_V_30_SEC "30 sec"
#define STR_V_1_MIN "1 min"
#define STR_V_2_MIN "2 min"
#define STR_V_3_MIN "3 min"
#define STR_V_4_MIN "4 min"
#define STR_V_5_MIN "5 min"
#define STR_V_6_MIN "6 min"
#define STR_V_7_MIN "7 min"
#define STR_V_8_MIN "8 min"
#define STR_V_9_MIN "9 min"
#define STR_V_15_MIN "15 min"
#define STR_MAIN_ONLY "MAIN\nONLY"
#define STR_DUAL_RX_RESPOND "DUAL RX\nRESPOND"
#define STR_CROSS_BAND "CROSS\nBAND"
#define STR_MAIN_TX_DUAL_RX "MAIN TX\nDUAL RX"
#define STR_TIME "TIME"
#define STR_CARRIER "CARRIER"
#define STR_STOP "STOP"
#define STR_FREQ "FREQ"
#define STR_CHANNEL_NUMBER "CHANNEL\nNUMBER"
#define STR_NAME "NAME"
#define STR_NAME_FREQ "NAME +\nFREQ"
#define STR_DO_NOTHING "DO\nNOTHING"
#define STR_RING "RING"
#define STR_REPLY "REPLY"
#define STR_BOTH "BOTH"
#define STR_UP_CODE "UP CODE"
#define STR_DOWN_CODE "DOWN CODE"
#define STR_UP_DOWN_CODE "UP+DOWN\nCODE"
#define STR_APOLLO_QUINDAR "APOLLO\nQUINDAR"
#define STR_ROGER_2 "ROGER"
#define STR_MDC_END "MDC\nEND"
#define STR_MDC_BGN "MDC\nBGN"
#define STR_MDC_BOTH "MDC\nBOTH"
#define STR_MDC_BGN_ROGER "MDC BGN\n+ROGER"
#define STR_VFO "VFO"
#define STR_ALL "ALL"
#define STR_DISABLE_ALL "DISABLE\nALL"
#define STR_UNLOCK_ALL "UNLOCK\nALL"
#define STR_V_5_SEC "5 sec"
#define STR_V_10_SEC "10 sec"
#define STR_V_20_SEC "20 sec"
#define STR_TX "TX"
#define STR_RX "RX"
#define STR_TX_RX "TX/RX"
#define STR_SCAN "Scan"
#define STR_LOW_VOL "LOW VOL"
#define STR_BUSY "BUSY"
#define STR_DISABLE "DISABLE"
#define STR_HIGH_VOL "HIGH VOL"
#define STR_PRESS_EXIT "Press EXIT"
#define STR_SAVE "SAVE?"
#define STR_SAVED "SAVED!"
#define STR_DEL "DEL?"
#define STR_LIST "List"
#define STR_CTCS "CTCS"
#define STR_DCS "DCS"
#define STR_PIC "PIC"
#define STR_TXT "TxT"
#define STR_F1SHRT "F1Shrt"
#define STR_F1LONG "F1Long"
#define STR_F2SHRT "F2Shrt"
#define STR_F2LONG "F2Long"
#define STR_M_LONG "M Long"
#define STR_LIGHT_2 "LIGHT"
#define STR_POWER "POWER"
#define STR_MONITOR "MONITOR"
#define STR_VOX "VOX"
#define STR_FM_RADIO "FM RADIO"
#define STR_LOCK_KEY "LOCK KEY"
#define STR_SWITCH_VFO "SWITCH VFO"
#define STR_VFO_MR "VFO/MR"
#define STR_DEMODU "Demodu"
#define STR_D_DECD "D Decd"
#define STR_W_N "W/N"
#define STR_WIDE "WIDE"
#define STR_NARROW "NARROW"
#define STR_MAIN_SEND "MAIN SEND"
#define STR_DUAL_SEND "DUAL SEND"
#define STR_PONMSG "POnMsg"
#define STR_RXLED "RxLED"

/* Existing ASCII identifiers retained for source compatibility. */
#define MDC_ID "MDC ID"
#define DTMF_ID "D ID"
#define Roger_1 "Roger 1\n(TPT)"
#define Roger_2 "Roger 2\n(TRBO)"
#define Roger_3 "Roger 3\n(GIRN)"
#define Roger_4 "Roger 4\n(MODT)"
#define Post_MDC "Post MDC"
#define Pre_MDC "Pre MDC"
#define Both_MDC "Both MDC"

#endif
